name: Packing Wordpress plugin app
run-name: ${{ github.actor }} is packing Wordpress plugin for ready download.

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Php composer
        uses: php-actions/composer@v6

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create package
        run: |
          mkdir lucky
          cp -r includes lucky
          cp -r assets lucky
          cp -r vendor lucky
          cp plugin.php lucky

      - name: Create zip file
        run: zip -r lucky.zip lucky/

      - name: Get version from package.json
        id: version
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check_tag
        run: |
          echo "tag_exists=$(git ls-remote --tag origin -l ${{ steps.version.outputs.version }})" >> $GITHUB_OUTPUT

      - name: Create Tag
        if: steps.check_tag.outputs.tag_exists == ''
        run: |
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "lucky.zip"
          tag: ${{ steps.version.outputs.version }}
          allowUpdates: true